//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassificationToolboxWPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grayScaleConversionImagePath {
            get {
                return ((string)(this["grayScaleConversionImagePath"]));
            }
            set {
                this["grayScaleConversionImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grayScaleConversionOutputPath {
            get {
                return ((string)(this["grayScaleConversionOutputPath"]));
            }
            set {
                this["grayScaleConversionOutputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int openMPthreads {
            get {
                return ((int)(this["openMPthreads"]));
            }
            set {
                this["openMPthreads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int progressBuffer {
            get {
                return ((int)(this["progressBuffer"]));
            }
            set {
                this["progressBuffer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int tplThreads {
            get {
                return ((int)(this["tplThreads"]));
            }
            set {
                this["tplThreads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string samplesPath {
            get {
                return ((string)(this["samplesPath"]));
            }
            set {
                this["samplesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastLogFolder {
            get {
                return ((string)(this["lastLogFolder"]));
            }
            set {
                this["lastLogFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cropImageSaveInFolder {
            get {
                return ((string)(this["cropImageSaveInFolder"]));
            }
            set {
                this["cropImageSaveInFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cropImageFolder {
            get {
                return ((string)(this["cropImageFolder"]));
            }
            set {
                this["cropImageFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string forRemovingFeaturesPath {
            get {
                return ((string)(this["forRemovingFeaturesPath"]));
            }
            set {
                this["forRemovingFeaturesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string featuresToShow {
            get {
                return ((string)(this["featuresToShow"]));
            }
            set {
                this["featuresToShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string negativeSamplesPath {
            get {
                return ((string)(this["negativeSamplesPath"]));
            }
            set {
                this["negativeSamplesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string positiveSamplesPath {
            get {
                return ((string)(this["positiveSamplesPath"]));
            }
            set {
                this["positiveSamplesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string featureSaveAs {
            get {
                return ((string)(this["featureSaveAs"]));
            }
            set {
                this["featureSaveAs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string learningClassifierPath {
            get {
                return ((string)(this["learningClassifierPath"]));
            }
            set {
                this["learningClassifierPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string learningFeaturesPath {
            get {
                return ((string)(this["learningFeaturesPath"]));
            }
            set {
                this["learningFeaturesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string testingClassifierResultPath {
            get {
                return ((string)(this["testingClassifierResultPath"]));
            }
            set {
                this["testingClassifierResultPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string testingClassifierPath {
            get {
                return ((string)(this["testingClassifierPath"]));
            }
            set {
                this["testingClassifierPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string testingFeaturesPath {
            get {
                return ((string)(this["testingFeaturesPath"]));
            }
            set {
                this["testingFeaturesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchResultFolder {
            get {
                return ((string)(this["batchResultFolder"]));
            }
            set {
                this["batchResultFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string detectionClassifierPath {
            get {
                return ((string)(this["detectionClassifierPath"]));
            }
            set {
                this["detectionClassifierPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string detectionImagePath {
            get {
                return ((string)(this["detectionImagePath"]));
            }
            set {
                this["detectionImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string detectionResultFolder {
            get {
                return ((string)(this["detectionResultFolder"]));
            }
            set {
                this["detectionResultFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchDetectionClassifierPath {
            get {
                return ((string)(this["batchDetectionClassifierPath"]));
            }
            set {
                this["batchDetectionClassifierPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchDetectionImageFolder {
            get {
                return ((string)(this["batchDetectionImageFolder"]));
            }
            set {
                this["batchDetectionImageFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchDetectionResultFolder {
            get {
                return ((string)(this["batchDetectionResultFolder"]));
            }
            set {
                this["batchDetectionResultFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string detectionFPfolder {
            get {
                return ((string)(this["detectionFPfolder"]));
            }
            set {
                this["detectionFPfolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchCropImageFolder {
            get {
                return ((string)(this["batchCropImageFolder"]));
            }
            set {
                this["batchCropImageFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchCropSaveInFolder {
            get {
                return ((string)(this["batchCropSaveInFolder"]));
            }
            set {
                this["batchCropSaveInFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchNegativeSamplesPath {
            get {
                return ((string)(this["batchNegativeSamplesPath"]));
            }
            set {
                this["batchNegativeSamplesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchPositiveSamplesPath {
            get {
                return ((string)(this["batchPositiveSamplesPath"]));
            }
            set {
                this["batchPositiveSamplesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchExtractionSaveInPath {
            get {
                return ((string)(this["batchExtractionSaveInPath"]));
            }
            set {
                this["batchExtractionSaveInPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string learningValidationFeaturesPath {
            get {
                return ((string)(this["learningValidationFeaturesPath"]));
            }
            set {
                this["learningValidationFeaturesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string testingImagePath {
            get {
                return ((string)(this["testingImagePath"]));
            }
            set {
                this["testingImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string batchResultFile {
            get {
                return ((string)(this["batchResultFile"]));
            }
            set {
                this["batchResultFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string learningResamplingFolder {
            get {
                return ((string)(this["learningResamplingFolder"]));
            }
            set {
                this["learningResamplingFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string featureExtractionImageFolder {
            get {
                return ((string)(this["featureExtractionImageFolder"]));
            }
            set {
                this["featureExtractionImageFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string featureImageSaveAs {
            get {
                return ((string)(this["featureImageSaveAs"]));
            }
            set {
                this["featureImageSaveAs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cropSamplesCoordinates {
            get {
                return ((string)(this["cropSamplesCoordinates"]));
            }
            set {
                this["cropSamplesCoordinates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string testingClassifierFolder {
            get {
                return ((string)(this["testingClassifierFolder"]));
            }
            set {
                this["testingClassifierFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string zernikeComparisonImage {
            get {
                return ((string)(this["zernikeComparisonImage"]));
            }
            set {
                this["zernikeComparisonImage"] = value;
            }
        }
    }
}
